- hosts: all
  vars:
    packagename: httpd
      
  tasks:
  - name: Ansible Dictionary Example
    debug:
      msg: "{{ packagename }}"
  - name: Ensure that Apache is installed
    yum: name={{packagename}} state=present
  - name: Start Apache Services
    service: name={{packagename}} enabled=yes state=started
